name: Create Release

on: 
  push:
    tags:
    - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build MIS
      run: mvn install -B
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "target/cloudgene-*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
